DROP ROLE IF EXISTS tasync;
CREATE ROLE tasync WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  PASSWORD '1234';
DROP DATABASE IF EXISTS tasync;
CREATE DATABASE tasync
    WITH
    OWNER = tasync
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;